// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Solver$BasicsLinkedinLearning = require("./Solver.bs.js");

var match = Solver$BasicsLinkedinLearning.quadraticSolver(1.0, -2.0, 1.0);

if (match !== undefined) {
  var match$1 = match;
  console.log("x1 = " + (match$1[0].toString() + (", x2 = " + match$1[1].toString())));
} else {
  console.log("Could not solve");
}

var nums = [
  23,
  13,
  0,
  2,
  45
];

var match$2 = Belt_Array.get(nums, 0);

if (match$2 !== undefined) {
  console.log(match$2);
} else {
  console.log("No such element.");
}

var numsTimesTwo = Belt_Array.map(nums, (function (e) {
        return (e << 1);
      }));

console.log(nums);

console.log(numsTimesTwo);

exports.nums = nums;
/* match Not a pure module */
