// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function quadraticSolver(a, b, c) {
  var discriminant = b * b - 4.0 * a * c;
  if (discriminant < 0.0) {
    return ;
  } else {
    var x1 = (-b + Math.sqrt(discriminant)) / 2.0 * a;
    var x2 = (-b - Math.sqrt(discriminant)) / 2.0 * a;
    return /* tuple */[
            x1,
            x2
          ];
  }
}

exports.quadraticSolver = quadraticSolver;
/* No side effect */
